server:
  port: 8093

app:
  kafka:
    topic: ipc-topic
    schema.registry.url: http://host.docker.internal:8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

spring:
  mvc:
    servlet:
      path: /seller    # Path added in ecs-gateway under predicates
  kafka:
    bootstrap-servers: host.docker.internal:9092
    consumer:
      group-id: ecs-seller

//*********** START: DO NOT CHANGE***********	  
cipher:
  key: TmFtZWVzaFkwVXJlTXlMIWZl
  iv: ESi6qJZS6/Q0IaDmLCFc1w==
//*********** END: DO NOT CHANGE ***********	  

rdbms:
  driver: org.postgresql.Driver
  user: ecsadmin
  pwd: M8XkzirhG6qVSFHscuINqg==
  url: jdbc:postgresql://ecs_db:3524/echikitsak
  default-schema: ecs_phamacy

hibernate:
  dialect: org.hibernate.dialect.PostgreSQLDialect
  format_sql: true

logging:
  level:
    org.apache.kafka: INFO
