server:
  port: 8097

//Topic naming convention: <team>.<service>.<event-type>.<entity>.<action>.<environment>.<version>
app:
  version: 1.0.0
  kafka:
    schema.registry.url: http://host.docker.internal:8081
    producers:
      topics:
        - support.support-service.event.feedback.created.dev.v1

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

spring:
  mvc:
    servlet:
      path: /support    # Path added in ecs-gateway under predicates
  kafka:
    admin:
      fail-fast: true
    bootstrap-servers: host.docker.internal:9092
    consumer:
      group-id: ecs-support
  data:
    mongodb:
      uri: mongodb://ecs-nosql-db:12921
      username: ecsadmin
      password: iT$2$ecreTF0ry0u
      ssl:
        enabled: true
        bundle: mongodb-ssl
      database: ecs
      authentication-database: ecs
  ssl:
    bundles:
      mongodb-ssl:
        truststore:
          path: /tmp/truststore.jks
          password: changeit
          type: JKS

//*********** START: DO NOT CHANGE***********	  
cipher:
  key: TmFtZWVzaFkwVXJlTXlMIWZl
  iv: ESi6qJZS6/Q0IaDmLCFc1w==
//*********** END: DO NOT CHANGE ***********	  

rdbms:
  driver: org.postgresql.Driver
  user: ecsadmin
  pwd: M8XkzirhG6qVSFHscuINqg==
  url: jdbc:postgresql://ecs_db:3524/ecs_support
  default-schema: ecs

hibernate:
  dialect: org.hibernate.dialect.PostgreSQLDialect
  format_sql: true

logging:
  level:
    org.apache.kafka: INFO
